# Generated by Django 5.2.8 on 2025-11-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_question_option1_question_option2_question_option3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
